### ISSUE TITLE
Can't edit subscription

### ISSUE THREAD

**Issue by jhwhite** [MiniCodeMonkey/curbside#37]
I created the subscription but there is no way I can edit it. I created it for Wegman's initially but now I want to go back and add Kroger.

Edit: Nor can I update my phone number.

**Comment by MiniCodeMonkey** [comment]
Those are both great questions! For subscriptions, simply sign up again and the previous preferences will be overwritten. To change your phone number, stop the subscription on the old phone number first and sign up again with the new one.

I have [updated the FAQ](http://curb.run/#faq) to address these questions as well.
