### ISSUE TITLE
Subscription created screen says monitoring 20 stores I only checked the box for 2

### ISSUE THREAD

**Issue by jhwhite** [MiniCodeMonkey/curbside#39]
I signed up with a second number and checked Wegman's and Kroger, then the created modal said I was being monitored for 20 stores.

![Curb Run-Get your grocery store curbside pickup](https://user-images.githubusercontent.com/1574572/79502851-38d31600-7ffe-11ea-909c-eb990230c792.png)

**Comment by mjwhansen** [comment]
Hi, that means it's scanning 20 nearby stores. It doesn't mean it's scanning 20 store brands.

**Comment by MiniCodeMonkey** [comment]
I can see how that is confusing. If we end up redesigning the signup flow, we'll probably visualize stores on a map with a circle for radius. That would probably make more sense.
